config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
    # sessions: 'users/sessions',
    # registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # devise_for :admins, :class_name => 'User'
  
  # get 'users/index'
  # resources :product

  root 'tops#index'
  get  "tops/json" => "tops#json"
  
  get 'users/profile'
  get 'users/index' => "users#index" 
   # ログアウト画面
   get 'users/logout' => "users#logout"
   # ユーザークレジットカード登録ページ
   get 'users/card' => "users#card"
   # お知らせページ
   get 'users/notification' => "users#notification"
   # やることリストページ
   get 'users/todo' => "users#todo"
   # 出品した商品
   get 'users/sell_will' => "users#sell_will"
   get 'users/sell_now' => "users#sell_now"
   get 'users/sell_was' => "users#sell_was"
   get 'products/:id/sell_detail' => "products#sell_detail"


   # 購入した商品-取引中ページ
   get 'users/purchase' => "users#purchase"
   # 購入した商品-過去の取引ページ
   get 'users/purchased' => "users#purchased"

  get  'products/:id/edit' => 'products#edit'
  patch "products/:id/update" => "products#update"
  patch "products/:id/buy" => "products#buy"
  get  'products/:id/details' => "products#details" 
  get  'products/get_category_children' => "products#get_category_children"
  get  'products/get_category_grandchildren' => "products#get_category_grandchildren"
  get  "products/get_size" => "products#get_size"
  get  'products/:id/confirm' => "products#confirm"
  get  'products/exhibit' =>"products#exhibit"
  get  'products/sell_modal' =>"products/sell_modal"
  post 'create' => "products#create"
  get  'products/imgexhibit' =>"products#imgexhibit"
  post 'items' => 'products#items'
  delete "products/:id/destroy" => "products#destroy"
  # 本人情報の登録
  get  'identifications/index' => "identifications#index"
  post 'identifications/create' => "identifications#create"
  post 'products/:id/pay' => 'products#pay', as: 'pay'
  
  # resources :products do
  #   collection do
  #     get "get_category_children"
  #     get "get_category_grandchildren"
  #     get "get_size"
  #     get "confirm"
  #     get "imgexhibit"
  #   end
  #   member do
  #     get "details"
  #     get "exhibit"  
  #   end
  # end

  resources :signup do
    collection do
      get 'registration'
      get 'detail_tel'
      get 'sns'
      get 'detail_zip'
      get 'detail_payment'  #入力が全て完了
      get 'detail_done'  #登録完了後
    end
  end


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController

  before_action :validates_step1, only: :detail_tel
  before_action :validates_step2, only: :detail_zip
  before_action :validates_step3, only: :detail_payment
  before_action :validates_step4, only: :detail_done

  protect_from_forgery :except => [:create]

  def registration
    @user = User.new
    
  end

  def sns
    @user = User.new
  end
  
  def detail_tel
    @user = User.new
    session[:nickname] = user_params[:nickname]
    session[:email] = user_params[:email]
    session[:password] = user_params[:password]
    session[:password_confirmation] = user_params[:password_confirmation]
    session[:last_name] = user_params[:last_name]
    session[:first_name] = user_params[:first_name]
    session[:last_name_kana] = user_params[:last_name_kana]
    session[:first_name_kana] = user_params[:first_name_kana] 
    session[:birth_year] = user_params[:birth_year]
    session[:birth_year] = user_params[:birth_year]
    session[:birth_month] = user_params[:birth_month]
    session[:birth_day] = user_params[:birth_day] 
  end

  def detail_zip
    session[:phone_number] = user_params[:phone_number]
    @user = User.new
  end

  def detail_payment
    session[:zipcode] = user_params[:zipcode]
    session[:prefecture] = user_params[:prefecture]
    session[:city] = user_params[:city]
    session[:address] = user_params[:address]
    session[:building] = user_params[:building]
    @user = User.new
  end

  def detail_done 
    session[:authorization_token] = user_params[:authorization_token]
    session[:security_code] = user_params[:security_code]
    session[:expiration_date_month] = user_params[:expiration_date_month]
    session[ :expiration_date_year] = user_params[:expiration_date_year]
    @user = User.new
  end

  

  def create
    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      last_name: session[:last_name], 
      first_name: session[:first_name], 
      last_name_kana: session[:last_name_kana], 
      first_name_kana: session[:first_name_kana], 
      birth_year: session[:birth_year],
      birth_month: session[:birth_month],
      birth_day: session[:birth_day],
      phone_number: session[:phone_number],
      zipcode: session[:zipcode],
      prefecture: session[:prefecture],
      city: session[:city],
      address: session[:address],
      building: session[:building],
      authorization_token: session[:authorization_token],
      security_code: session[:security_code],
      expiration_date_month: session[:expiration_date_month],
      expiration_date_year: session[:expiration_date_year]
    )
   
    if @user.save
      session[:id] = @user.id
      sign_in User.find(session[:id]) unless user_signed_in?
      redirect_to  root_path
    else
      render '/signup/registration'
    end
  end

  

  private
  def user_params
    params.require(:user).permit(
      :nickname,
      :email, 
      :password, 
      :password_confirmation, 
      :last_name,
      :first_name, 
      :last_name_kana, 
      :first_name_kana, 
      :birth_year, 
      :birth_month, 
      :birth_day, 
      :phone_number,
      :zipcode,
      :prefecture,
      :city,
      :address,
      :building,
      :authorization_token,
      :security_code,
      :expiration_date_month,
      :expiration_date_year
    )
  end

  def validates_step1
    session[:nickname] = user_params[:nickname]
    session[:email] = user_params[:email]
    session[:password] = user_params[:password]
    session[:password_confirmation] = user_params[:password_confirmation]
    session[:last_name] = user_params[:last_name]
    session[:first_name] = user_params[:first_name]
    session[:last_name_kana] = user_params[:last_name_kana]
    session[:first_name_kana] = user_params[:first_name_kana] 
    @user = User.new(
      nickname: session[:nickname], 
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      first_name: session[:first_name], 
      last_name_kana: session[:last_name_kana], 
      first_name_kana: session[:first_name_kana],
      last_name: session[:last_name]
    )
    render '/signup/registration' unless @user.valid?(:validates_step1)
    
  end


  def validates_step2
    session[:phone_number] = user_params[:phone_number]
    @user = User.new(
      nickname: session[:nickname], 
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      first_name: session[:first_name], 
      last_name_kana: session[:last_name_kana], 
      first_name_kana: session[:first_name_kana],
      last_name: session[:last_name],
      phone_number: session[:phone_number]
    )
    render '/signup/detail_tel' unless @user.valid?(:validates_step2)
  end

  def validates_step3
    session[:zipcode] = user_params[:zipcode]
    session[:prefecture] = user_params[:prefecture]
    session[:city] = user_params[:city]
    session[:address] = user_params[:address]
    session[:building] = user_params[:building]
    @user = User.new(
      nickname: session[:nickname], 
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      first_name: session[:first_name], 
      last_name_kana: session[:last_name_kana], 
      first_name_kana: session[:first_name_kana],
      last_name: session[:last_name],
      phone_number: session[:phone_number],
      zipcode: session[:zipcode],
      prefecture: session[:prefecture],
      city: session[:city],
      address: session[:address],
      building: session[:building]
    )
    render '/signup/detail_zip' unless @user.valid?(:validates_step3)
  end

  def validates_step4
    session[:authorization_token] = user_params[:authorization_token]
    session[:security_code] = user_params[:security_code]
    session[:expiration_date_month] = user_params[:expiration_date_month]
    session[ :expiration_date_year] = user_params[:expiration_date_year]
    @user= User.new(
      nickname: session[:nickname], 
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      first_name: session[:first_name], 
      last_name_kana: session[:last_name_kana], 
      first_name_kana: session[:first_name_kana],
      last_name: session[:last_name],
      phone_number: session[:phone_number],
      zipcode: session[:zipcode],
      prefecture: session[:prefecture],
      city: session[:city],
      address: session[:address],
      building: session[:building],
      authorization_token: session[:authorization_token],
      security_code: session[:security_code],
      expiration_date_month: session[:expiration_date_month],
      expiration_date_year: session[:expiration_date_year]
    )
    
    render '/signup/detail_payment' unless @user.valid?(:validates_step4)
  end
 


 

end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/signup/detail_done.html.haml
.us-body
  .us-body__header
    = render partial: 'users/us-body__header'
    .progress-bar
      = render partial: 'users/progress-bar'
  .us-body__main-registration
    .us-body__main-registration__container
      .us-body__main-registration__container__head
        .title 会員登録完了
      .us-body__main-registration__container__form
        .us-body__main-registration__container__form__content
          .form-group
            %h2  ありがとうございます。
            %h2  会員登録が完了しました。
          = form_for(@user, url:  signup_index_path, method: :post) do |f|
            = f.submit "メルカリをはじめる",class: 'btn-default btn-red'
          
        .registration_logo
          .registration_logo__head-box
            .registration_logo__head-box-left
              %h2 スマホでかんたんフリマアプリ
              %p#font  今すぐ無料ダウンロード !
              .head-box-left__logo
                = image_tag 'mercari_icon.png', size: "40x40"
                %ul.head-box-left__logo__app
                  %li
                    = link_to image_tag("app-store.svg"), "#"
                  %li
                    = link_to image_tag("google-play.svg"), "#"
            .head-box-right
              = image_tag "download_content_pc.png"
  .us-body__footer
    = render partial: 'users/us-body__footer'

app/views/signup/detail_payment.html.haml
.us-body
  .us-body__header
    = render partial: 'users/us-body__header'
    .progress-bar
      = render partial: 'users/progress-bar'
  .us-body__main-registration
    .us-body__main-registration__container
      .us-body__main-registration__container__head
        .title 支払い方法
      = form_for(@user, url: detail_done_signup_index_path ,method: :get,  html: {class:'us-body__main-registration__container__form'}) do |f|
        = hidden_field_tag :current_step, 'detail_payment'
        .us-body__main-registration__container__form__content
          .form-group
            %label.form-group__label カード番号
            %span.form-group__require 必須
            = f.text_field :authorization_token, placeholder: "半角数字のみ" , class:'input-default'
            = render partial: 'devise/shared/error_messages', locals: {user: @user, column: "authorization_token"}

            .signup-card-list
              %li= image_tag "visa.svg"
              %li= image_tag "master-card.svg"
              %li= image_tag "saison-card.svg"
              %li= image_tag "jcb.svg"
              %li= image_tag "american_express.svg"
              %li= image_tag "dinersclub.svg"
              %li= image_tag "discover.svg"
          .form-group
            %div
              %label.form-group__label 有効期限
              %span.form-group__require 必須
            .expiration_date
              = f.select :expiration_date_month,[*1..12], {},{id:"expiration_date_month", class:'input-default-half'}
              = render partial: 'devise/shared/error_messages', locals: {user: @user, column: "expiration_date_month"}
              %i.fa.fa-chevron-down.select-wrap-wrap
              %span 月
            .expiration_date
              = f.select :expiration_date_year,[*2019..2039], {},{id:"expiration_date_year", class:'input-default-half'}
              = render partial: 'devise/shared/error_messages', locals: {user: @user, column: "expiration_date_year"}
              %i.fa.fa-chevron-down.select-wrap-wrap
              %span 年
          .form-group
            %label.form-group__label セキュリティコード
            %span.form-group__require 必須
            = f.text_field :security_code, placeholder: "カード背面4桁もしくは3桁の番号" , class:'input-default'
            = render partial: 'devise/shared/error_messages', locals: {user: @user, column: "security_code"}
            .form-group.text-right
              %p
                = link_to '#' do
                  カード裏面の番号とは？
          = f.submit "次へ進む", class: 'btn-default btn-red',type: "submit"
  .us-body__footer
    = render partial: 'users/us-body__footer'

app/views/signup/detail_tel.html.haml
.us-body
  .us-body__header
    = render partial: 'users/us-body__header'
    .progress-bar
      = render partial: 'users/progress-bar'
  .us-body__main-registration
    .us-body__main-registration__container
      .us-body__main-registration__container__head
        .title 電話番号の確認
      = form_for(@user, url: detail_zip_signup_index_path, method: :get, html: {class:'us-body__main-registration__container__form'}) do |f|
        .us-body__main-registration__container__form__content
          .form-group
            %label.form-group__label 携帯電話の番号
            = f.text_field :phone_number, placeholder: "携帯電話の番号を入力", class:'input-default'
          = render partial: 'devise/shared/error_messages', locals: {user: @user, column: "phone_number"}
              
          %p 本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
          = f.submit "SMSを送信する", class: 'btn-default btn-red',type: "submit"
          %p ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
          .form-group.text-right
            %p
              = link_to '#' do
                電話番号の確認が必要な理由
                = fa_icon"angle-right", class:'angle'
  .us-body__footer
    = render partial: 'users/us-body__footer'

app/views/signup/detail_zip.html.haml
.us-body
  .us-body__header
    = render partial: 'users/us-body__header'
    .progress-bar
      = render partial: 'users/progress-bar'
  .us-body__main-registration
    .us-body__main-registration__container
      .us-body__main-registration__container__head
        .title 住所入力
      = form_for(@user, url: detail_payment_signup_index_path, method: :get, html: {class:'us-body__main-registration__container__form'}) do |f|
        = hidden_field_tag :current_step, 'detail_zip'
        .us-body__main-registration__container__form__content
          .form-group
            %label.form-group__label お名前
            %span.form-group__require 必須
            = f.text_field :last_name, placeholder: "例) 山田" ,  class:'input-default-zip'
            = f.text_field :first_name,  placeholder: "例) 彩" , class:'input-default-zip'
            = render partial: 'devise/shared/error_messages', locals: {user: @user, column: "last_name"}
            = render partial: 'devise/shared/error_messages', locals: {user: @user, column: "first_name"}


          .form-group
            %label.form-group__label お名前カナ
            %span.form-group__require 必須
            = f.text_field :last_name_kana,  placeholder: "例) ヤマダ" , class:'input-default-zip'
            = f.text_field :first_name_kana, placeholder: "例) アヤ" , class:'input-default-zip'
          .form-group
            %label.form-group__label 郵便番号
            %span.form-group__require 必須
            = f.text_field :zipcode, placeholder: "例) 123−4567" , class:'input-default'
            = render partial: 'devise/shared/error_messages', locals: {user: @user, column: "zipcode"}

          .form-group
            %label.form-group__label 都道府県
            %span.form-group__require 必須
            .input-default-selects
              %i.fa.fa-chevron-down.select-wrap-wrap
              = f.select :prefecture ,User.prefectures.keys.to_a
              = render partial: 'devise/shared/error_messages', locals: {user: @user, column: "prefecture"}

          .form-group
            %label.form-group__label 市区町村
            %span.form-group__require 必須
            = f.text_field :city, placeholder: "例) 横浜市緑区" , class:'input-default'
            = render partial: 'devise/shared/error_messages', locals: {user: @user, column: "city"}

          .form-group
            %label.form-group__label 番地
            %span.form-group__require 必須
            = f.text_field :address, placeholder: "例) 青山1−1−1" , class:'input-default'
            = render partial: 'devise/shared/error_messages', locals: {user: @user, column: "address"}

          .form-group
            %label.form-group__label 建物名
            %span.form-group__require.option 任意
            = f.text_field :building, placeholder: "例) 柳ビル103" , class:'input-default'
          .form-group
            %label.form-group__label 電話
            %span.form-group__require.option 任意
            %input{type:"text", placeholder: "例) 090−1234−5678" , name:"phone_number2" , class:'input-default'}
          = f.submit "次へ進む", class: 'btn-default btn-red',type: "submit"
  .us-body__footer
    = render partial: 'users/us-body__footer'

app/views/signup/registration.html.haml
.us-body
  .us-body__header
    = render partial: 'users/us-body__header'
    .progress-bar
      = render partial: 'users/progress-bar'
  .us-body__main-registration
    .us-body__main-registration__container
      .us-body__main-registration__container__head
        .title 会員情報入力
      = form_for(@user, url: detail_tel_signup_index_path, method: :get, html: {class:'us-body__main-registration__container__form'}) do |f|
        = hidden_field_tag :current_step, 'registration'
        .us-body__main-registration__container__form__content
          .form-group
            %label.form-group__label ニックネーム
            %span.form-group__require 必須
            = f.text_field :nickname, placeholder: "例) メルカリ太郎", class:'input-default'
            = render partial: 'devise/shared/error_messages', locals: {user: @user, column: "nickname"}

          .form-group
            %label.form-group__label メールアドレス
            %span.form-group__require 必須
            = f.email_field :email, placeholder: "PC・携帯どちらでも可" , class:'input-default'
            = render partial: 'devise/shared/error_messages', locals: {user: @user, column: "email"}
          .form-group
            %label.form-group__label パスワード
            %span.form-group__require 必須
            = f.password_field :password, placeholder: "7文字以上" , class:'input-default'
            = render partial:  'devise/shared/error_messages', locals: {user: @user, column: "password"}
          .form-group
            %label.form-group__label パスワード (確認)
            %span.form-group__require 必須
            = f.password_field :password_confirmation, placeholder: "7文字以上" , class:'input-default'
            = render partial:  'devise/shared/error_messages', locals: {user: @user, column: "password_confirmation"}
          .form-group
            .form-group__sub-head 本人確認
            .form-group__text
            安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。

            .form-group
              %div
                %label.form-group__label お名前(全角)
                %span.form-group__require 必須
              = f.text_field :last_name, placeholder: "例) 山田" , class:'input-default-half'
              = f.text_field :first_name, placeholder: "例) 彩" , class:'input-default-half'
              = render partial:  'devise/shared/error_messages', locals: {user: @user , column: "first_name"}
              = render partial:  'devise/shared/error_messages', locals: {user:@user , column: "last_name"}
            .form-group
              %div
                %label.form-group__label お名前カナ(全角)
                %span.form-group__require 必須
              = f.text_field :last_name_kana, placeholder: "例) ヤマダ" , class:'input-default-half'
              = f.text_field :first_name_kana, placeholder: "例) アヤ" ,  class:'input-default-half'
            = render partial:  'devise/shared/error_messages', locals: {user:@user , column: "last_name_kana"}
            = render partial:  'devise/shared/error_messages', locals: {user:@user , column: "first_name_kana"}
            .form-group
              %label.form-group__label 生年月日
              %span.form-group__require 必須
              .birthday-select-wrap
                .select-wrap
                  .select-wrap-wrap
                    %i.fa.fa-chevron-down.select-wrap-wrap
                    =f.select :birth_year,[*1900..2019], {},{:id=>"year", :style => "width: 80px;"}
                    %span{:style => "margin-left: 3px; margin-right: 5px; display: inline-block;"} 年
                    
                .select-wrap
                  .select-wrap-wrap
                    %i.fa.fa-chevron-down.select-wrap-wrap
                    =f.select :birth_month, [*1..12], {}, {:id=>"month", :style => "width: 80px;"}
                    %span{:style => "margin-left: 3px; margin-right: 5px; display: inline-block;"} 月
                    
                .select-wrap
                  .select-wrap-wrap
                    %i.fa.fa-chevron-down.select-wrap-wrap
                    =f.select :birth_day, [*1..31],{}, {:id=>"day", :style => "width: 80px;"}
                    %span{:style => "margin-left: 3px; margin-right: 5px; display: inline-block;"} 日
              
            .form-group__info-text
              ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
        .us-body__main-registration__container__form__content
          .form-group
            = recaptcha_tags
          .form-group
            %p.form-group__text.text-center
              「次へ進む」のボタンを押すことにより、
              %a{href:"#", :target => "blank"}利用規約
              に同意したものとみなします
          = f.submit "次へ進む", class: 'btn-default btn-red',type: "submit"
          .form-group.text-right
            %p
              = link_to '#' do
                本人情報の登録について
                = fa_icon"angle-right", class:'angle'
  .us-body__footer
    = render partial: 'users/us-body__footer'

app/views/signup/sns.html.haml
.us-body
  .us-body__header
    = render partial: 'users/us-body__header'
    .progress-bar
      = render partial: 'users/progress-bar'
  .us-body__main-registration
    .us-body__main-registration__container
      .us-body__main-registration__container__head
        .title 会員情報入力
      = form_for(@user, url: detail_tel_signup_index_path, method: :get, html: {class:'us-body__main-registration__container__form'}) do |f|
        = hidden_field_tag :current_step, 'sns'
        .us-body__main-registration__container__form__content
          .form-group
            %label.form-group__label ニックネーム
            %span.form-group__require 必須
            = f.text_field :nickname, placeholder: "例) メルカリ太郎", class:'input-default',value: session[:nickname]
            = render partial: 'devise/shared/error_messages', locals: {user: @user, column: "nickname"}

          .form-group
            %label.form-group__label メールアドレス
            %span.form-group__require 必須
            = f.email_field :email, placeholder: "PC・携帯どちらでも可" , class:'input-default',value: session[:email]
            = render partial: 'devise/shared/error_messages', locals: {user: @user, column: "email"}
          .form-group
            %label.form-group__label パスワード
            %span.form-group__require 必須
            = f.password_field :password, placeholder: "7文字以上" , class:'input-default'
            = render partial:  'devise/shared/error_messages', locals: {user: @user, column: "password"}
          .form-group
            %label.form-group__label パスワード (確認)
            %span.form-group__require 必須
            = f.password_field :password_confirmation, placeholder: "7文字以上" , class:'input-default'
            = render partial:  'devise/shared/error_messages', locals: {user: @user, column: "password_confirmation"}
          .form-group
            .form-group__sub-head 本人確認
            .form-group__text
            安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。

            .form-group
              %div
                %label.form-group__label お名前(全角)
                %span.form-group__require 必須
              = f.text_field :last_name, placeholder: "例) 山田" , class:'input-default-half'
              = f.text_field :first_name, placeholder: "例) 彩" , class:'input-default-half'
              = render partial:  'devise/shared/error_messages', locals: {user: @user , column: "first_name"}
              = render partial:  'devise/shared/error_messages', locals: {user:@user , column: "last_name"}
            .form-group
              %div
                %label.form-group__label お名前カナ(全角)
                %span.form-group__require 必須
              = f.text_field :last_name_kana, placeholder: "例) ヤマダ" , class:'input-default-half'
              = f.text_field :first_name_kana, placeholder: "例) アヤ" ,  class:'input-default-half'
            = render partial:  'devise/shared/error_messages', locals: {user:@user , column: "last_name_kana"}
            = render partial:  'devise/shared/error_messages', locals: {user:@user , column: "first_name_kana"}
            .form-group
              %label.form-group__label 生年月日
              %span.form-group__require 必須
              .birthday-select-wrap
                .select-wrap
                  .select-wrap-wrap
                    %i.fa.fa-chevron-down.select-wrap-wrap
                    =f.select :birth_year,[*1900..2019], {},{:id=>"year", :style => "width: 80px;"}
                    %span{:style => "margin-left: 3px; margin-right: 5px; display: inline-block;"} 年
                    
                .select-wrap
                  .select-wrap-wrap
                    %i.fa.fa-chevron-down.select-wrap-wrap
                    =f.select :birth_month, [*1..12], {}, {:id=>"month", :style => "width: 80px;"}
                    %span{:style => "margin-left: 3px; margin-right: 5px; display: inline-block;"} 月
                    
                .select-wrap
                  .select-wrap-wrap
                    %i.fa.fa-chevron-down.select-wrap-wrap
                    =f.select :birth_day, [*1..31],{}, {:id=>"day", :style => "width: 80px;"}
                    %span{:style => "margin-left: 3px; margin-right: 5px; display: inline-block;"} 日
              
            .form-group__info-text
              ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
        .us-body__main-registration__container__form__content
          .form-group
            = recaptcha_tags
          .form-group
            %p.form-group__text.text-center
              「次へ進む」のボタンを押すことにより、
              %a{href:"#", :target => "blank"}利用規約
              に同意したものとみなします
          = f.submit "次へ進む", class: 'btn-default btn-red',type: "submit"
          .form-group.text-right
            %p
              = link_to '#' do
                本人情報の登録について
                = fa_icon"angle-right", class:'angle'
  .us-body__footer
    = render partial: 'users/us-body__footer'