config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
    # sessions: 'users/sessions',
    # registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # devise_for :admins, :class_name => 'User'
  
  # get 'users/index'
  # resources :product

  root 'tops#index'
  get  "tops/json" => "tops#json"
  
  get 'users/profile'
  get 'users/index' => "users#index" 
   # ログアウト画面
   get 'users/logout' => "users#logout"
   # ユーザークレジットカード登録ページ
   get 'users/card' => "users#card"
   # お知らせページ
   get 'users/notification' => "users#notification"
   # やることリストページ
   get 'users/todo' => "users#todo"
   # 出品した商品
   get 'users/sell_will' => "users#sell_will"
   get 'users/sell_now' => "users#sell_now"
   get 'users/sell_was' => "users#sell_was"
   get 'products/:id/sell_detail' => "products#sell_detail"


   # 購入した商品-取引中ページ
   get 'users/purchase' => "users#purchase"
   # 購入した商品-過去の取引ページ
   get 'users/purchased' => "users#purchased"

  get  'products/:id/edit' => 'products#edit'
  patch "products/:id/update" => "products#update"
  patch "products/:id/buy" => "products#buy"
  get  'products/:id/details' => "products#details" 
  get  'products/get_category_children' => "products#get_category_children"
  get  'products/get_category_grandchildren' => "products#get_category_grandchildren"
  get  "products/get_size" => "products#get_size"
  get  'products/:id/confirm' => "products#confirm"
  get  'products/exhibit' =>"products#exhibit"
  get  'products/sell_modal' =>"products/sell_modal"
  post 'create' => "products#create"
  get  'products/imgexhibit' =>"products#imgexhibit"
  post 'items' => 'products#items'
  delete "products/:id/destroy" => "products#destroy"
  # 本人情報の登録
  get  'identifications/index' => "identifications#index"
  post 'identifications/create' => "identifications#create"
  post 'products/:id/pay' => 'products#pay', as: 'pay'
  
  # resources :products do
  #   collection do
  #     get "get_category_children"
  #     get "get_category_grandchildren"
  #     get "get_size"
  #     get "confirm"
  #     get "imgexhibit"
  #   end
  #   member do
  #     get "details"
  #     get "exhibit"  
  #   end
  # end

  resources :signup do
    collection do
      get 'registration'
      get 'detail_tel'
      get 'sns'
      get 'detail_zip'
      get 'detail_payment'  #入力が全て完了
      get 'detail_done'  #登録完了後
    end
  end


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable,
          :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  def self.without_sns_data(auth)
    user = User.where(email: auth.info.email).first

      if user.present?
        sns = SnsCredential.create(
          uid: auth.uid,
          provider: auth.provider,
          user_id: user.id
        )
      else
        user = User.new(
          nickname: auth.info.name,
          email: auth.info.email,
        )
        sns = SnsCredential.new(
          uid: auth.uid,
          provider: auth.provider
        )
      end
      return { user: user ,sns: sns}
    end

    def self.with_sns_data(auth, snscredential)
    user = User.where(id: snscredential.user_id).first
    unless user.present?
      user = User.new(
        nickname: auth.info.name,
        email: auth.info.email,
      )
    end
    return {user: user}
    end

    def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = with_sns_data(auth, snscredential)[:user]
      sns = snscredential
    else
      user = without_sns_data(auth)[:user]
      sns = without_sns_data(auth)[:sns]
    end
    return { user: user ,sns: sns}
  end

  enum prefecture: {
  "---------": 0,北海道: 1,青森県: 2,岩手県: 3,宮城県: 4,秋田県: 5,山形県: 6,福島県: 7,
  茨城県: 8,栃木県: 9,群馬県: 10,埼玉県: 11,千葉県: 12,東京都: 13,神奈川県: 14,
  新潟県: 15,富山県: 16,石川県: 17,福井県: 18,山梨県: 19,長野県: 20,
  岐阜県: 21,静岡県: 22,愛知県: 23,三重県: 24,
  滋賀県: 25,京都府: 26,大阪府: 27,兵庫県: 28,奈良県: 29,和歌山県: 30,
  鳥取県: 31,島根県: 32,岡山県: 33,広島県: 34,山口県: 35,
  徳島県: 36,香川県: 37,愛媛県: 38,高知県: 39,
  福岡県: 40,佐賀県: 41,長崎県: 42,熊本県: 43,大分県: 44,宮崎県: 45,鹿児島県: 46,沖縄県: 47
  }

  has_one :profile, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :sns_credentials, dependent: :destroy
  has_many :seller_products, class_name: 'Product', :foreign_key => 'seller_id'
  has_many :buyer_products, class_name: 'Product', :foreign_key => 'buyer_id'

  # VALID_EMAIL_REGEX =                 /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :nickname,                presence: true, length: {maximum: 20}, on: :validates_step1
  validates :email,                   presence: true, uniqueness: true, on: :validates_step1
  validates :password,                presence: true, length: {minimum: 7, maximum: 128}, on: :validates_step1
  validates :password_confirmation,   presence: true, length: {minimum: 7, maximum: 128}, on: :validates_step1
  validates :first_name,              presence: true, on: :validates_step1
  validates :last_name,               presence: true, on: :validates_step1
  validates :first_name_kana,         presence: true, on: :validates_step1
  validates :last_name_kana,          presence: true, on: :validates_step1
  validates :phone_number,            presence: true, on: :validates_step2
  validates :zipcode,                 presence: true, on: :validates_step3, format: {with: /\A[0-9]{3}-[0-9]{4}\z/}
  validates :prefecture,              presence: true, on: :validates_step3
  validates :city,                    presence: true, on: :validates_step3
  validates :address,                 presence: true, on: :validates_step3
  validates :authorization_token,     presence: true, on: :validates_step4, format: {with: /\A\d{14,16}\z/  }
  validates :security_code,           presence: true, on: :validates_step4, format: {with: /\A\d{3,4}\z/ }
  validates :expiration_date_month,   presence: true, on: :validates_step4
  validates :expiration_date_year,    presence: true, on: :validates_step4
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end


  def callback_for(provider)
    @omniauth = request.env['omniauth.auth']
    info = User.find_oauth(@omniauth)
    @user = info[:user]
    if @user.persisted? 
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    
    else 
      @sns = info[:sns]
      session[:nickname] = @user.nickname
      session[:email] = @user.email
      session[:password] = @user.password
      session[:provider] = provider.to_s
      session[:uid] = request.env["omniauth.auth"].uid
      redirect_to sns_signup_index_path
  
    end
  end

  def failure
    redirect_to root_path and return
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  
  def index
    @nickname = current_user.nickname
  end

  def profile
  end
  
  def logout 
    @user = User.new
  end

  def card
  end

  def exhibit
  end

  def notification
  end

  def todo
  end

  def sell_will
    @product = Product.where(seller_id: current_user.id).order("created_at DESC")
    @product.each do |product|
      @image = product.images[0].url.url
    end
  end

  def sell_now
    @product = Product.where(seller_id: current_user.id).order("created_at DESC")
    @product.each do |product|
      @image = product.images[0].url.url
    end

  end

  def sell_was
    @product = Product.where(seller_id: current_user.id).order("created_at DESC")
    @product.each do |product|
      @image = product.images[0].url.url
    end
  end

  def purchase
    @product = Product.where(buyer_id: current_user.id).order("created_at DESC")
    @product.each do |product|
      @image = product.images[0].url.url
    end
  end

  def purchased
    @product = Product.where(seller_id: current_user.id).order("created_at DESC")
    @product.each do |product|
      @image = product.images[0].url.url
    end
  end

 

  def create
    @user = User.new(user_params)
    @user.save
    render action: :detail_tel
  end

 

  private
  def user_params
    params.require(:user).permit(
      :nickname,
      :email, 
      :password, 
      address_attributes:[:id, :last_name, :first_name, :last_name_kana, :first_name_kana, :birth_year, :birth_month, :birth_day]
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_mypage__right--head.html.haml
%section.user-icon
  = link_to "#" do
    %figure
    %h2.bold 
      = @nickname
    .mypage-number
      .mypage-numuber__hyoka
        評価
        %span 3
      .mypage-number__syuppin
        出品数
        %span 0

app/views/users/_mypage__right--middle.html.haml
.mypage-tag-notification-todo
  %ul.mypage-tabs
    %li.mypage-tab.active{id: 'list'}
      お知らせ
    %li.mypage-tab{id: 'todo'}
      やることリスト
%ul.tab-contents
  %li.tab-content.show
    .tab-content__list
      .tab-content__list--icon
      .tab-content__list--textfield
        .tab-content__list--textfield--text
          《速報》今なら販売手数料が実質無料！出品が超お得♪
        .tab-content__list--textfield--time
          .tab-content__list--ttextfield--time--icon
            🕛
          .tab-content__list--textfield--time--text
            1日前
      = fa_icon "chevron-right" , class: "allow"

    .tab-content__list
      .tab-content__list--icon
      .tab-content__list--textfield
        .tab-content__list--textfield--text
          《速報》今なら販売手数料が実質無料！出品が超超お得♪
        .tab-content__list--textfield--time
          .tab-content__list--ttextfield--time--icon
            🕛
          .tab-content__list--textfield--time--text
            1日前
      = fa_icon "chevron-right" , class: "allow"

    .tab-content__list
      .tab-content__list--icon
      .tab-content__list--textfield
        .tab-content__list--textfield--text
          《速報》今なら販売手数料が実質無料！出品が超超超お得♪
        .tab-content__list--textfield--time
          .tab-content__list--ttextfield--time--icon
            🕛
          .tab-content__list--textfield--time--text
            1日前
      = fa_icon "chevron-right" , class: "allow"

    .tab-content__list
      .tab-content__list--icon
      .tab-content__list--textfield
        .tab-content__list--textfield--text
          《速報》今なら販売手数料が実質無料！出品が超超超超お得♪
        .tab-content__list--textfield--time
          .tab-content__list--ttextfield--time--icon
            🕛
          .tab-content__list--textfield--time--text
            1日前
      = fa_icon "chevron-right" , class: "allow"

    .tab-content__list
      .tab-content__list--icon
      .tab-content__list--textfield
        .tab-content__list--textfield--text
          《速報》今なら販売手数料が実質無料！出品が超超超超超超超超超超超超超超超超超超超超超超超超超超超超超超お得♪
        .tab-content__list--textfield--time
          .tab-content__list--ttextfield--time--icon
            🕛
          .tab-content__list--textfield--time--text
            1日前
      = fa_icon "chevron-right" , class: "allow"

    .tab-content__go-list
      = link_to users_notification_path do
        %p 
          一覧を見る

  %li.tab-content
    .tab-content__todo
      %ul.tab-content__todo--contents
        %li.tab-content__todo--information
          現在、やることリストはありません

app/views/users/_progress-bar.html.haml
.progress
  .progress__item
    .progress__title.progress--done 会員情報
    .progress__dot.progress--done
      .fa.fa-circle
      .progress__line.progress__user
  .progress__item
    .progress__title.progress__user 電話番号認証
    .progress__dot.progress__user
      .fa.fa-circle
      .progress__line.progress__tel
  .progress__item
    .progress__title.progress__tel お届け先住所入力
    .progress__dot.progress__tel
      .fa.fa-circle
      .progress__line.progress__address
  .progress__item
    .progress__title.progress__address 支払い方法
    .progress__dot.progress__address
      .fa.fa-circle
      .progress__line.progress__peymethod
  .progress__item
    .progress__title.progress__peymethod 完了
    .progress__dot.progress__peymethod
      .fa.fa-circle

app/views/users/_side-bar.html.haml
.mypage__left
  .mypage__left--list
    %ul
      %li.mypage__left--list--item
        = link_to users_index_path do
          %p 
            マイページ
            = fa_icon "chevron-right" , class: "allow"
      %li.mypage__left--list--item
        = link_to users_notification_path do
          %p 
            お知らせ
            = fa_icon "chevron-right" , class: "allow"
      %li.mypage__left--list--item
        = link_to users_todo_path do
          %p 
            やることリスト
            = fa_icon "chevron-right" , class: "allow"
      %li.mypage__left--list--item
        = link_to "#" do
          %p 
            いいね！一覧
            = fa_icon "chevron-right" , class: "allow"
      %li.mypage__left--list--item
        = link_to products_exhibit_path do
          %p 
            出品する
            = fa_icon "chevron-right" , class: "allow"
      %li.mypage__left--list--item
        = link_to users_sell_will_path do
          %p 
            出品した商品 - 出品中
            = fa_icon "chevron-right" , class: "allow"
      %li.mypage__left--list--item
        = link_to users_sell_now_path do
          %p 
            出品した商品 - 取引中
            = fa_icon "chevron-right" , class: "allow"
      %li.mypage__left--list--item
        = link_to users_sell_was_path do
          %p 
            出品した商品 - 売却済み
            = fa_icon "chevron-right" , class: "allow"
      %li.mypage__left--list--item
        = link_to users_purchase_path do
          %p 
            購入した商品 - 取引中
            = fa_icon "chevron-right" , class: "allow"
      %li.mypage__left--list--item
        = link_to users_purchased_path do
          %p 
            購入した商品 - 過去の取引
            = fa_icon "chevron-right" , class: "allow"
      %li.mypage__left--list--item
        = link_to "#" do
          %p 
            ニュース一覧
            = fa_icon "chevron-right" , class: "allow"
      %li.mypage__left--list--item
        = link_to "#" do
          %p 
            評価一覧
            = fa_icon "chevron-right" , class: "allow"
      %li.mypage__left--list--item
        = link_to "#" do
          %p 
            ガイド
            = fa_icon "chevron-right" , class: "allow"
      %li.mypage__left--list--item
        = link_to "#" do
          %p 
            お問い合わせ
            = fa_icon "chevron-right"
    %h3.mypage__left--list--head メルペイ
    %ul
      %li.mypage__left--list--item
        = link_to "#" do
          %p
            売上・振込申請
            = fa_icon "chevron-right" , class: "allow"
      %li.mypage__left--list--item
        = link_to "#" do
          %p
            ポイント
            = fa_icon "chevron-right" , class: "allow"
    %h3.mypage__left--list--head 設定
    %ul
      %li.mypage__left--list--item
        = link_to users_profile_path do
          %p
            プロフィール
            = fa_icon "chevron-right" , class: "allow"
      %li.mypage__left--list--item
        = link_to "#" do
          %p
            発送元・お届け先住所変更
            = fa_icon "chevron-right" , class: "allow"
      %li.mypage__left--list--item
        = link_to users_card_path do
          %p
            お支払い方法 
            = fa_icon "chevron-right" , class: "allow"
      %li.mypage__left--list--item
        = link_to "#" do
          %p
            メール/パスワード
            = fa_icon "chevron-right" , class: "allow"
      %li.mypage__left--list--item
        = link_to  identifications_index_path do
          %p 
            本人情報
            = fa_icon "chevron-right" , class: "allow"
      %li.mypage__left--list--item
        = link_to "#" do
          %p
            電話番号の確認
            = fa_icon "chevron-right" , class: "allow"
      %li.mypage__left--list--item
        = link_to users_logout_path do
          %p 
            ログアウト
            = fa_icon "chevron-right" , class: "allow"

app/views/users/_us-body__footer.html.haml
.us-body__footer__nav
  .us-body__footer__nav__clear-fix
    %a{href: '#',class:"li"} プライバシーポリシー
    %a{href: '#',class:"li"} メルカリ利用規約
    %a{href: '#',class:"li"} 特定商取引に関する表記
.us-body__footer__logo
  = link_to image_tag(src= "logo-gray.svg", class: "us-body__footer__logo__img"),root_path
.us-body__footer__copyright
  %small.us-body__footer__copyright__context © 2019 Mercari

app/views/users/_us-body__header.html.haml
.us-body__header__iconform
  = link_to root_path do
    = image_tag "mercari_logo.svg"

app/views/users/card.html.haml
.body
  = render partial: 'tops/header/head'
  .pankuzu
    - breadcrumb :card
    = breadcrumbs separator: " &rsaquo; "
  = render partial: 'layouts/syuppinn'
  .mid
    .side
      = render partial: 'users/side-bar'
    .main
      %h2.user
        支払い方法
      .main-content
        %section
          .single-content
            %h3 クレジットカード一覧
          %ul
            %li
              %form.single-content{action: "users/card/delete", method: "post"}
                .card-logo
                  = image_tag "jcb.svg", size: "26x20"
                .number 
                  **************0000
                .number.deadline
                  12 / 30
                %button{type: "submit", class: "remove-btn"}
                  削除する
        .payment-method
          = link_to  "#"  do
            %p お支払い方法について
            = fa_icon "chevron-right"  
  = render partial: 'tops/bottoms/bottom'

app/views/users/index.html.haml
.body
  .body__next
    = render partial: 'layouts/syuppinn'
    .head
      = render partial: 'tops/header/head'
    .pankuzu
      - breadcrumb :user
      = breadcrumbs separator: " &rsaquo; "
    .mypages
      .mypage
        .mypage__right
          .mypage__right--head
            = render partial: 'users/mypage__right--head'
          .mypage__right--middle
            = render partial: 'users/mypage__right--middle'
          .mypage__right--foot
            = render partial: 'users/mypage__right--foot'
        .mypage__left
          = render partial: 'users/side-bar'
    .bottom
      = render partial: 'tops/bottoms/bottom'

app/views/users/notification.html.haml
.body
  .body__next
    = render partial: 'layouts/syuppinn'
    .head
      = render partial: 'tops/header/head'
    .pankuzu
      - breadcrumb :todo
      = breadcrumbs separator: " &rsaquo; "
    .rock
      .mypage
        .mypage__right

          .mypage__right--middle
            .mypage-tag-notification-todo
              %ul.mypage-tabs
                %li.mypage-tab.active{id: 'list'}
                  お知らせ
                %li.mypage-tab{id: 'todo'}
                  やることリスト
            %ul.tab-contents
              %li.tab-content.show
                .tab-content__list
                  .tab-content__list--icon
                  .tab-content__list--textfield
                    .tab-content__list--textfield--text
                      《速報》今なら販売手数料が実質無料！出品が超お得♪
                    .tab-content__list--textfield--time
                      .tab-content__list--ttextfield--time--icon
                        🕛
                      .tab-content__list--textfield--time--text
                        1日前
                  = fa_icon "chevron-right" , class: "allow"
              
        .mypage__left
          = render partial: 'users/side-bar'
    .bottom
      = render partial: 'tops/bottoms/bottom'

app/views/users/profile.html.haml
.body
  .body--next
    = render partial: 'layouts/syuppinn'
    .body__next--top--head
      = render partial: 'tops/header/head'
    .pankuzu
      - breadcrumb :profile
      = breadcrumbs separator: " &rsaquo; "
    .profile
      .profile__left
        = render partial: 'users/side-bar'
      .profile__right
        .profile__right--chapterhead
          プロフィール
        .profile__right--setting
          .profile__right--setting--imgimg
          .profile__right--setting--formform
            %input{type: "text",value: "okaponさん",name: "nickname",placeholder: "例)AYA★セール中"}
        .profile__right--cont
          .profile__right--cont--textform
            %textarea.textarea-default{:name => "introduction", :placeholder => "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪"}
          .profile__right--cont--editbutton
            = link_to "#" do
              %button.profile__right--cont--editbutton{:type => "submit"}変更する
  .body__next--top--header--bottom
    = render partial: 'tops/bottoms/bottom'

app/views/users/purchase.html.haml
.body
  .body__next
    = render partial: 'layouts/syuppinn'
    .head
      = render partial: 'tops/header/head'
    .pankuzu
      - breadcrumb :todo
      = breadcrumbs separator: " &rsaquo; "
    .rock
      .mypage
        .mypage__right
          #purchase
            %section.bought-list
              %h2.bought-list__top 購入した商品
              
              %ul.bought-list__tab-heads
                = link_to users_purchase_path do
                  %li.bought-list__tab-heads--head{id: 'purchase_now'}
                    取引中
                = link_to users_purchased_path do
                  %li.bought-list__tab-heads--head{id: 'puschase_was'}
                    過去の取引

              %ul.bought-list__contents
                - if @product.present?
                  %ul.tab-contents
                    %li.tab-content.show
                      - @product.each do |product|
                        = link_to "/products/#{product.id}/sell_detail" do 
                          .tab-content__list
                            .tab-content__list--icon
                              = image_tag product.images[0].url.url,size: "50x50"
                            .tab-content__list--textfield
                              .tab-content__list--textfield--text
                                = product.name
                              .tab-content__list--textfield--time
                                .tab-content__list--ttextfield--time--icon
                                  ❤️
                                .tab-content__list--textfield--time--text
                                  1
                                .tab-content__list--ttextfield--time--icon
                                  💭
                                .tab-content__list--textfield--time--text
                                  1
                                .tab-content__list--textfield--time--text--status
                                  出品中
                            = fa_icon "chevron-right" , class: "allow"
                - else
                  %ul.bought-list__contents
                    %li.bought-list__contents--content.show
                      %ul.bought-list__contents--content--purchase--contents
                        %li.bought-list__contents--content--purchase--information
                          取引中の商品がありません
        .mypage__left
          = render partial: 'users/side-bar'
    .bottom
      = render partial: 'tops/bottoms/bottom'

app/views/users/purchased.html.haml
.body
  .body__next
    = render partial: 'layouts/syuppinn'
    .head
      = render partial: 'tops/header/head'
    .pankuzu
      - breadcrumb :todo
      = breadcrumbs separator: " &rsaquo; "
    .rock
      .mypage
        .mypage__right
          #purchased
            %section.bought-list
              %h2.bought-list__top 購入した商品

              %ul.bought-list__tab-heads
                = link_to users_purchase_path do
                  %li.bought-list__tab-heads--head{id: 'purchase_now'}
                    取引中
                = link_to users_purchased_path do
                  %li.bought-list__tab-heads--head{id: 'purchase_was'}
                    過去の取引

                  
              %ul.bought-list__contents
                - if @product.present?
                  %ul.tab-contents
                    %li.tab-content.show
                      - @product.each do |product|
                        = link_to "/products/#{product.id}/sell_detail" do 
                          .tab-content__list
                            .tab-content__list--icon
                              = image_tag product.images[0].url.url,size: "50x50"
                            .tab-content__list--textfield
                              .tab-content__list--textfield--text
                                = product.name
                              .tab-content__list--textfield--time
                                .tab-content__list--ttextfield--time--icon
                                  ❤️
                                .tab-content__list--textfield--time--text
                                  1
                                .tab-content__list--ttextfield--time--icon
                                  💭
                                .tab-content__list--textfield--time--text
                                  1
                                .tab-content__list--textfield--time--text--status
                                  出品中
                            = fa_icon "chevron-right" , class: "allow"
                - else
                  %li.bought-list__contents--content.show
                    %ul.bought-list__contents--content--purchased--contents
                      %li.bought-list__contents--content--purchased--information
                        過去に取引した商品がありません
        .mypage__left
          = render partial: 'users/side-bar'
    .bottom
      = render partial: 'tops/bottoms/bottom'

app/views/users/sell_now.html.haml
.body
  .body__next
    = render partial: 'layouts/syuppinn'
    .head
      = render partial: 'tops/header/head'
    .pankuzu
      - breadcrumb :user
      = breadcrumbs separator: " &rsaquo; "
    .mypages
      .mypage
        .mypage__right
          #sell_now        
            %section.bought-list
              %h2.bought-list__top 出品した商品

              %ul.bought-list__tab-heads
                = link_to users_sell_will_path do
                  %li.bought-list__tab-heads--head{id: 'sellwill'}
                    出品中
                = link_to users_sell_now_path do
                  %li.bought-list__tab-heads--head{id: 'sellnow'}
                    取引中
                = link_to users_sell_was_path do
                  %li.bought-list__tab-heads--head{id: 'sellwas'}
                    売却済み

              %ul.bought-list__contents
                - if @product.present?
                  %ul.tab-contents
                    %li.tab-content.show
                      - @product.each do |product|
                        = link_to "/products/#{product.id}/sell_detail" do 
                          .tab-content__list
                            .tab-content__list--icon
                              = image_tag product.images[0].url.url,size: "50x50"
                            .tab-content__list--textfield
                              .tab-content__list--textfield--text
                                = product.name
                              .tab-content__list--textfield--time
                                .tab-content__list--ttextfield--time--icon
                                  ❤️
                                .tab-content__list--textfield--time--text
                                  1
                                .tab-content__list--ttextfield--time--icon
                                  💭
                                .tab-content__list--textfield--time--text
                                  1
                                .tab-content__list--textfield--time--text--status
                                  出品中
                            = fa_icon "chevron-right" , class: "allow"
                - else 
                  %li.bought-list__contents--content.show
                    %ul.bought-list__contents--content--purchased--contents
                      %li.bought-list__contents--content--purchased--information
                        取引中の商品がありません
        .mypage__left
          = render partial: 'users/side-bar'
    .bottom
      = render partial: 'tops/bottoms/bottom'

app/views/users/todo.html.haml
.body
  .body__next
    = render partial: 'layouts/syuppinn'
    .head
      = render partial: 'tops/header/head'
    .pankuzu
      - breadcrumb :todo
      = breadcrumbs separator: " &rsaquo; "
    .rock
      .mypage
        .mypage__right

          .mypage__right--middle
            .mypage-tag-notification-todo
              %ul.mypage-tabs
                %li.mypage-tab
                  お知らせ
                %li.mypage-tab.active
                  やることリスト
            %ul.tab-contents
              %li.tab-content.show
                .tab-content__todo
                  %ul.tab-content__todo--contents
                    %li.tab-content__todo--information
                      現在、やることリストはありません

        .mypage__left
          = render partial: 'users/side-bar'
    .bottom
      = render partial: 'tops/bottoms/bottom'