config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
    # sessions: 'users/sessions',
    # registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # devise_for :admins, :class_name => 'User'
  
  # get 'users/index'
  # resources :product

  root 'tops#index'
  get  "tops/json" => "tops#json"
  
  get 'users/profile'
  get 'users/index' => "users#index" 
   # ログアウト画面
   get 'users/logout' => "users#logout"
   # ユーザークレジットカード登録ページ
   get 'users/card' => "users#card"
   # お知らせページ
   get 'users/notification' => "users#notification"
   # やることリストページ
   get 'users/todo' => "users#todo"
   # 出品した商品
   get 'users/sell_will' => "users#sell_will"
   get 'users/sell_now' => "users#sell_now"
   get 'users/sell_was' => "users#sell_was"
   get 'products/:id/sell_detail' => "products#sell_detail"


   # 購入した商品-取引中ページ
   get 'users/purchase' => "users#purchase"
   # 購入した商品-過去の取引ページ
   get 'users/purchased' => "users#purchased"

  get  'products/:id/edit' => 'products#edit'
  patch "products/:id/update" => "products#update"
  patch "products/:id/buy" => "products#buy"
  get  'products/:id/details' => "products#details" 
  get  'products/get_category_children' => "products#get_category_children"
  get  'products/get_category_grandchildren' => "products#get_category_grandchildren"
  get  "products/get_size" => "products#get_size"
  get  'products/:id/confirm' => "products#confirm"
  get  'products/exhibit' =>"products#exhibit"
  get  'products/sell_modal' =>"products/sell_modal"
  post 'create' => "products#create"
  get  'products/imgexhibit' =>"products#imgexhibit"
  post 'items' => 'products#items'
  delete "products/:id/destroy" => "products#destroy"
  # 本人情報の登録
  get  'identifications/index' => "identifications#index"
  post 'identifications/create' => "identifications#create"
  post 'products/:id/pay' => 'products#pay', as: 'pay'
  
  # resources :products do
  #   collection do
  #     get "get_category_children"
  #     get "get_category_grandchildren"
  #     get "get_size"
  #     get "confirm"
  #     get "imgexhibit"
  #   end
  #   member do
  #     get "details"
  #     get "exhibit"  
  #   end
  # end

  resources :signup do
    collection do
      get 'registration'
      get 'detail_tel'
      get 'sns'
      get 'detail_zip'
      get 'detail_payment'  #入力が全て完了
      get 'detail_done'  #登録完了後
    end
  end


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/identifications_controller.rb
class IdentificationsController < ApplicationController
  def index
    @user = Profile.new()
  end

  def create
    @user = Profile.new(profile_params)
    @user.save
  end

  private
  def profile_params
    params.require(:profile).permit(:zipcode, :prefecture, :city , :address, :building).merge(seller_id: current_user.id)
  end
end

app/helpers/identifications_helper.rb
module IdentificationsHelper
end

app/views/identifications/index.html.haml
.body
  = render partial: 'tops/header/head'
  .pankuzu
    - breadcrumb :identification
    = breadcrumbs separator: " &rsaquo; "
  = render partial: 'layouts/syuppinn'
  .mid
    .side
      = render partial: 'users/side-bar'
    .main
      %h2.user 
        本人情報の登録
      .main-content
        %p#line
          お客さまの本人情報をご登録ください。
          %br
          登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
        %p.right
          = link_to "#" do
            本人確認書類のアップロードについて
            = fa_icon "chevron-right" , class: "chevron"
        .form-group
          %label お名前
          %p 山田 勇気
        .form-group
          %label お名前カナ
          %p ヤマダ ユウキ
        .form-group
          %label 生年月日
          %p 1990/1/1
        = form_for @user, url: identifications_create_path do |f|
          .form-group
            %label 郵便番号
            %span.nin 任意
            = f.text_field :zipcode, placeholder: "例）1234567"
          .form-group
            %label 都道府県
            %span.nin 任意
            .select-wrap
              = fa_icon "angle-down"
              = f.select :prefecture ,Profile.prefectures.keys.to_a
          .form-group
            %label 市区町村
            %span.nin 任意
            = f.text_field :city, placeholder:  "例）横浜市緑区"
          .form-group
            %label 番地
            %span.nin 任意
            = f.text_field :address , placeholder: "例）青山1−1−1"
          .form-group
            %label 建物名
            %span.nin 任意
            = f.text_field :building, placeholder: "例）柳ビル103"
          = f.submit " 登録する", class: "btn-red"
          .form-group  
            %p.right
              = link_to  "本人情報の登録について" , "#"
              = fa_icon "chevron-right"
= render partial: 'tops/bottoms/bottom'