config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
    # sessions: 'users/sessions',
    # registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # devise_for :admins, :class_name => 'User'
  
  # get 'users/index'
  # resources :product

  root 'tops#index'
  get  "tops/json" => "tops#json"
  
  get 'users/profile'
  get 'users/index' => "users#index" 
   # ログアウト画面
   get 'users/logout' => "users#logout"
   # ユーザークレジットカード登録ページ
   get 'users/card' => "users#card"
   # お知らせページ
   get 'users/notification' => "users#notification"
   # やることリストページ
   get 'users/todo' => "users#todo"
   # 出品した商品
   get 'users/sell_will' => "users#sell_will"
   get 'users/sell_now' => "users#sell_now"
   get 'users/sell_was' => "users#sell_was"
   get 'products/:id/sell_detail' => "products#sell_detail"


   # 購入した商品-取引中ページ
   get 'users/purchase' => "users#purchase"
   # 購入した商品-過去の取引ページ
   get 'users/purchased' => "users#purchased"

  get  'products/:id/edit' => 'products#edit'
  patch "products/:id/update" => "products#update"
  patch "products/:id/buy" => "products#buy"
  get  'products/:id/details' => "products#details" 
  get  'products/get_category_children' => "products#get_category_children"
  get  'products/get_category_grandchildren' => "products#get_category_grandchildren"
  get  "products/get_size" => "products#get_size"
  get  'products/:id/confirm' => "products#confirm"
  get  'products/exhibit' =>"products#exhibit"
  get  'products/sell_modal' =>"products/sell_modal"
  post 'create' => "products#create"
  get  'products/imgexhibit' =>"products#imgexhibit"
  post 'items' => 'products#items'
  delete "products/:id/destroy" => "products#destroy"
  # 本人情報の登録
  get  'identifications/index' => "identifications#index"
  post 'identifications/create' => "identifications#create"
  post 'products/:id/pay' => 'products#pay', as: 'pay'
  
  # resources :products do
  #   collection do
  #     get "get_category_children"
  #     get "get_category_grandchildren"
  #     get "get_size"
  #     get "confirm"
  #     get "imgexhibit"
  #   end
  #   member do
  #     get "details"
  #     get "exhibit"  
  #   end
  # end

  resources :signup do
    collection do
      get 'registration'
      get 'detail_tel'
      get 'sns'
      get 'detail_zip'
      get 'detail_payment'  #入力が全て完了
      get 'detail_done'  #登録完了後
    end
  end


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  
  belongs_to :category
  has_many   :likes
  has_many   :images, inverse_of: :product, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  has_many   :comments
  belongs_to :seller, class_name: 'User', :foreign_key => 'seller_id'
  belongs_to :buyer, class_name: 'User', :foreign_key => 'buyer_id', optional: true

  # enum state: {
  #   "---": 0, 新品未使用: 1, 未使用に近い: 2,目立った傷や汚れなし: 3, やや傷や汚れあり: 4, 傷や汚れあり: 5, 全体的に状態が悪い: 6
  # }
  # enum shipping_fee: {
  #   "---": 0, "送料込み(出品者負担)": 1, "着払い(購入者負担)": 2
  # }
  # enum shipping_date: {
  #   "---":0, "1~2で発送":1, "2~3で発送":2, "4~7で発送":3
  # }
  # enum shipping_region: {
  #   "---": 0,北海道: 1,青森県: 2,岩手県: 3,宮城県: 4,秋田県: 5,山形県: 6,福島県: 7,
  #   茨城県: 8,栃木県: 9,群馬県: 10,埼玉県: 11,千葉県: 12,東京都: 13,神奈川県: 14,
  #   新潟県: 15,富山県: 16,石川県: 17,福井県: 18,山梨県: 19,長野県: 20,
  #   岐阜県: 21,静岡県: 22,愛知県: 23,三重県: 24,
  #   滋賀県: 25,京都府: 26,大阪府: 27,兵庫県: 28,奈良県: 29,和歌山県: 30,
  #   鳥取県: 31,島根県: 32,岡山県: 33,広島県: 34,山口県: 35,
  #   徳島県: 36,香川県: 37,愛媛県: 38,高知県: 39,
  #   福岡県: 40,佐賀県: 41,長崎県: 42,熊本県: 43,大分県: 44,宮崎県: 45,鹿児島県: 46,沖縄県: 47
  # }

  enum state: {
    "新品未使用": 1, "未使用に近い": 2,"目立った傷や汚れなし": 3, "やや傷や汚れあり": 4, "傷や汚れあり": 5, "全体的に状態が悪い": 6
  }
  enum shipping_fee: {
    "送料込み(出品者負担)": 1, "着払い(購入者負担)": 2
  }
  enum shipping_date: {
    "1~2で発送": 1, "2~3で発送": 2, "4~7で発送": 3
  }
  enum shipping_region: {
    北海道: 1,青森県: 2,岩手県: 3,宮城県: 4,秋田県: 5,山形県: 6,福島県: 7,
    茨城県: 8,栃木県: 9,群馬県: 10,埼玉県: 11,千葉県: 12,東京都: 13,神奈川県: 14,
    新潟県: 15,富山県: 16,石川県: 17,福井県: 18,山梨県: 19,長野県: 20,
    岐阜県: 21,静岡県: 22,愛知県: 23,三重県: 24,
    滋賀県: 25,京都府: 26,大阪府: 27,兵庫県: 28,奈良県: 29,和歌山県: 30,
    鳥取県: 31,島根県: 32,岡山県: 33,広島県: 34,山口県: 35,
    徳島県: 36,香川県: 37,愛媛県: 38,高知県: 39,
    福岡県: 40,佐賀県: 41,長崎県: 42,熊本県: 43,大分県: 44,宮崎県: 45,鹿児島県: 46,沖縄県: 47
  }

  validates      :name,            presence: true, on: :validates_product
  validates      :description,     presence: true, on: :validates_product
  validates      :size,            presence: true, on: :validates_product
  validates      :brand,           presence: true, on: :validates_product
  validates      :state,           presence: true, on: :validates_product
  validates      :shipping_fee,    presence: true, on: :validates_product
  validates      :shipping_region, presence: true, on: :validates_product
  validates      :shipping_date,   presence: true, on: :validates_product
  validates      :category_id,     presence: true, on: :validates_product
  validates      :price,           presence: true, on: :validates_product, numericality: { only_integer: true , greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:exhibit, :confirm]
  before_action :validates_product, only: [:items]

  def exhibit
    @product = Product.new
    @product.images.build
    @category_parent_array = []
    Category.where(ancestry: nil).each do |parent|
     @category_parent_array << parent.name
    end
  end

   
  def json
  end

  def edit
    @product = Product.find_by(id: params[:id])

    @category_parent_array = ["---"]
    Category.where(ancestry: nil).each do |parent|
     @category_parent_array << parent.name
    end
    # @product_ids = @product

    @images =  @product.images
    
  end

  def update
    @product = Product.find(params[:id])
    if @product.seller_id == current_user.id
      @product.update(create_params)
      redirect_to root_path
    end
  end

  def buy
    @product = Product.find(params[:id])
    @product.update(buyer_id: current_user.id)
    redirect_to root_path
  end

  def confirm
    @product = Product.find_by(id: params[:id])
  end

  def details
    @product = Product.find_by(id: params[:id])
  end
 
  def create
    @product = Product.new(create_params)
    @product.save
  end
  
  def listingcompleted
  end

  def sell_detail
    @product = Product.find(params[:id])

    # (buyer_id: current_user.id)(buyer_id: current_user.id)

  end

  def destroy
    @product = Product.find(params[:id])
    if @product.seller_id == current_user.id
      @product.destroy
      redirect_to root_path
    end
  end


  # def items
  #   @product = Product.new(create_params2)
  #   if @product.save
  #     params[:image][:images].each do |image|
  #       #buildのタイミングは、newアクションでも可能かもしれません。buildすることで、saveした際にアソシエーション先のテーブルにも値を反映できるようになります。
  #       @product.images.build
  #       product_image = @product.images.new(url: image)
  #       product_image.save
  #     end
  #       #今回は、Ajaxのみの通信で実装するためHTMLへrespondする必要がないため、jsonのみです。
  #   end
  #   respond_to do |format|
  #     format.json
  #     format.html
  #   end
  # end


  def new
   @category_parent_array = ["---"]
   Category.where(ancestry: nil).each do |parent|
    @category_parent_array << parent.name
   end
  end

  def get_category_children
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def get_size
    selected_grandchild = Category.find("#{params[:grandchild_id]}") 
    if selected_grandchild.sizes[0] 
       related_size_parent = selected_grandchild.sizes[0] 
       @sizes = related_size_parent.children
    else
       selected_child = Category.find("#{params[:grandchild_id]}").parent 
       if related_size_parent = selected_child.sizes[0] 
          @sizes = related_size_parent.children 
       end
    end
  end

  def pay
    @product = Product.find_by(id: params[:id])
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    charge = Payjp::Charge.create(
    :amount => @product.price,
    :card => params['payjp-token'],
    :currency => 'jpy',
    )
    @product[:buyer_id] = current_user.id
    @product.save
    redirect_to root_path
  end


  private
    def create_params
      params.require(:product).permit(
        :name, 
        :description,
        :size, 
        :brand, 
        :state, 
        :shipping_fee, 
        :shipping_region,
        :shipping_date, 
        :price,
        :category_id,
        images_attributes: [:url,:_destroy,:id]).merge(seller_id: current_user.id)
    end


    def validates_product
      @category_parent_array = []
      Category.where(ancestry: nil).each do |parent|
        @category_parent_array << parent.name
      end

      @product = Product.new(
        name: params[:product][:name],
        description: params[:product][:description],
        size: params[:product][:size],
        brand: params[:product][:brand], 
        state: params[:product][:state], 
        shipping_fee: params[:product][:shipping_fee], 
        shipping_region: params[:product][:shipping_region],
        shipping_date: params[:product][:shipping_date], 
        price: params[:product][:price],
        category_id: params[:product][:category_id],
        seller_id: current_user.id
      )
      @product.images.build
      render '/products/exhibit' unless @product.valid?(:validates_product)
    end 
    
    def products_params
      params.require(:category).permit(:url, :name, :description)
    end


    def create_params2
      # images以外の値についてのストロングパラメータの設定
      item_params = params.require(:product).permit(:name, :description, :category_id, :size, :brand, :condition, :shipping_fee, :shipping_region, :shipping_date, :state, :price).merge(seller_id: current_user.id)
      return item_params
    end


    # def image_params
    #   #imageのストロングパラメータの設定.js側でimagesをrequireすれば画像のみを引き出せるように設定する。
    #   params.require(:image).permit({:url => []})
    # end
   
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_itembox.html.haml
.itembox
  .itembox__photobox
  .itembox__itembody
    .itembox__itembody--productsname
      ＊新品＊男女兼用＊b one soul＊ダックデュード＊GORIRA
      .itembox__itembody--productsname--smoke
    .itembox__itembody--pricebox
      .itembox__itembody--pricebox--price
        ¥ASK
      .itembox__itembody--pricebox--fonts
        .itembox__itembody--pricebox--fonts--hearts
          = fa_icon"heart-o"
        .itembox__itembody--pricebox--fonts--counts
          2
      

app/views/products/_itemconteiner.html.haml
.itemconteiner
  .itemconteiner__itemcategory
    okaponさんのその他の出品
  .itemconteiner__itemconteiner2
    .itemconteiner__itemconteiner2--itembox1
      = render partial: 'products/itembox'
    .itemconteiner__itemconteiner2--itembox2
      = render partial: 'products/itembox'
    .itemconteiner__itemconteiner2--itembox3
      = render partial: 'products/itembox'
    .itemconteiner__itemconteiner2--itembox4
      = render partial: 'products/itembox'
    .itemconteiner__itemconteiner2--itembox5
      = render partial: 'products/itembox'
    .itemconteiner__itemconteiner2--itembox6
      = render partial: 'products/itembox'

app/views/products/_listingcompleted.html.haml
.modal
  .modal__bg
  .modal2
    .modal2__listing
      .modal2__listing--completed
        出品が完了しました
    .modal2__continue
      .modal2__continue--text
        あなたが出品した商品は「出品した商品一覧」からいつでも見ることができます。
      = link_to "続けて出品する", products_exhibit_path,class:'modal2__continue--button'
      = link_to "商品ページへ行ってシェアする", root_path,class:'modal2__continue--text2'
      

app/views/products/_sell_modal.html.haml
.modal23
  .modal__bg2
  .modal22
    .modal22__listing2
      .modal22__listing2--completed2
        削除してもよろしいですか？
    .modal22__continue2
      .modal22__continue2--text2
        YES   or   NO
      .modal22__continue2--yesornobox
        .modal22__continue2--yesornobox--yesicon
          .modal22__continue2--yesornobox--yesicon--yesyes
            = link_to "YES", "/products/#{@product.id}/destroy", method: :delete
        .modal22__continue2--yesornobox--noicon
          .modal22__continue2--yesornobox--noicon--nonono
            NO
      = link_to "topページに戻る", root_path,class:'modal22__continue2--toptoptop'

      
      

app/views/products/confirm.html.haml
.body
  .body__next
    = render partial: 'users/us-body__header'
  .body__singlemain
    .body__singlemain--container
      .body__singlemain--container--confirm
        購入内容の確認
      .body__singlemain--container--confirmbox
        .body__singlemain--container--confirmbox--products
          = image_tag @product.images[0].url.url, class: "body__singlemain--container--confirmbox--products--photo"
          .body__singlemain--container--confirmbox--products--itemname
            = @product.name
        .body__singlemain--container--confirmbox--money
          .body__singlemain--container--confirmbox--money--moneybox
            = number_with_delimiter(@product.price, :delimiter => ',')
          .body__singlemain--container--confirmbox--money--postage
            送料込み
        .body__singlemain--container--confirmbox--point
          ポイントはありません
        .body__singlemain--container--confirmbox--price
          .body__singlemain--container--confirmbox--price--left
            支払い金額
          .body__singlemain--container--confirmbox--price--right
            = number_with_delimiter(@product.price, :delimiter => ',')
        = form_tag(action: :pay, method: :post) do
          %script{type: "text/javascript", src: "https://checkout.pay.jp", class:"payjp-button", "data-text": "購入する", "data-key": ENV['PEYJP_PUBLIC_KEY']}
        .body__singlemain--container--confirmbox--buycard
      .body__singlemain--container--userinfo
        .body__singlemain--container--userinfo--inner
          .body__singlemain--container--userinfo--inner--shipping
            配送先
          .body__singlemain--container--userinfo--inner--address
            = current_user.zipcode
            %br/
            = current_user.prefecture
            = current_user.city
            = current_user.address
            = current_user.building
           
            %br/
            = current_user.nickname
          .body__singlemain--container--userinfo--inner--fix
            .body__singlemain--container--userinfo--inner--fix--text
              変更する
            .body__singlemain--container--userinfo--inner--fix--icon
              = fa_icon"chevron-right"
      .body__singlemain--container--payment
        .body__singlemain--container--payment--inner
          .body__singlemain--container--payment--inner--method
            支払い方法
          .body__singlemain--container--payment--inner--text
            **************0000
            %br/
            09/38
          .body__singlemain--container--payment--inner--credit
            = image_tag "jcb.svg", size: "26x20"
          .body__singlemain--container--payment--inner--fix
            .body__singlemain--container--payment--inner--fix--text
              変更する
            .body__singlemain--container--payment--inner--fix--icon
              = fa_icon"chevron-right"
  .body__bottom
    = render partial: 'users/us-body__footer'

          

app/views/products/details.html.haml
.body
  .body__next
    = render partial: 'tops/header/head'
  .body__itembox
    .body__itembox--productname
      = @product.name
    .body__itembox--conteiner
      .body__itembox--conteiner--pic
        .body__itembox--conteiner--pic
          %ul.slider-for
            - @product.images.each do |image|
              %li 
                = image_tag image.url
          %ul.slider-nav
            - @product.images.each do |image|
              %li.slick-slide
                = image_tag image.url

      .body__itembox--conteiner--table
        %table{:border => "1", :bordercolor => "#f5f5f5", :cellpadding => "5", :cellspacing => "0", :width => "300"}
          %tr
            %th{:bgcolor => "#fafafa",:width => "117.5",:height => "70"}
              %font{:size => "2"} 出品者
            %td{:bgcolor => "#ffffff",:width => "182",:height => "71"}
              %font{:size => "2",:color => "blue"} 
                = link_to @product.seller.nickname,"#"
          %tr
            %th{:bgcolor => "#fafafa",:width => "117.5",:height => "73"}
              %font{:size => "2"} カテゴリー
            %td{:bgcolor => "#ffffff",:width => "182",:height => "71"}
              %font{:size => "2",:color => "blue"}
                = @product.category.parent.parent.name
                %br/
                = @product.category.parent.name
                %br/
                = @product.category.name
          %tr
            %th{:bgcolor => "#fafafa",:width => "117.5",:height => "46"}
              %font{:size => "2"} ブランド
            %td{:bgcolor => "#ffffff",:width => "182",:height => "46"}
              %font{:size => "2",:color => "blue"}
                = link_to @product.brand,"#"
          %tr
            %th{:bgcolor => "#fafafa",:width => "117.5",:height => "46"}
              %font{:size => "2"} 商品の状態
            %td{:bgcolor => "#ffffff",:width => "182",:height => "46"}
              %font{:size => "2"}
                = @product.state
          %tr
            %th{:bgcolor => "#fafafa",:width => "117.5",:height => "46"}
              %font{:size => "2"} 配送料の負担
            %td{:bgcolor => "#ffffff",:width => "182",:height => "46"}
              %font{:size => "2"}
                = @product.shipping_fee
          %tr
            %th{:bgcolor => "#fafafa",:width => "117.5",:height => "46"}
              %font{:size => "2"} 配送の方法
            %td{:bgcolor => "#ffffff",:width => "182",:height => "46"}
              %font{:size => "2"} 未定
          %tr
            %th{:bgcolor => "#fafafa",:width => "117.5",:height => "46"}
              %font{:size => "2"} 配送元地域
            %td{:bgcolor => "#ffffff",:width => "182",:height => "46"}
              %font{:size => "2"} 
                = link_to @product.shipping_region,"#"
          %tr
            %th{:bgcolor => "#fafafa",:width => "117.5",:height => "46"}
              %font{:size => "2"} 発送日の目安
            %td{:bgcolor => "#ffffff",:width => "182",:height => "46"}
              %font{:size => "2"}
                = @product.shipping_date
    .body__itembox--price
      .body__itembox--price--price2
        ¥
        =  number_with_delimiter(@product.price, :delimiter => ',')
      .body__itembox--price--price3
        (税込)
      .body__itembox--price--price4
        送料込み
        
    - if user_signed_in? && @product.seller.id == current_user.id
    - elsif user_signed_in? && @product.buyer_id.present?
      .sell-gray
        .sell-gray__font
          売り切れました
    - else
      .body__itembox--buybtn
        = link_to "購入画面に進む", "/products/#{@product.id}/confirm"
    .body__itembox--detail
      %p.body__itembox--detail
        = @product.description
    .body__itembox--btnconteiner
      .body__itembox--btnconteiner--left
        .body__itembox--btnconteiner--left--likebtn
          .body__itembox--btnconteiner--left--likebtn--heart
            = fa_icon"heart-o"
          .body__itembox--btnconteiner--left--likebtn--text
            いいね!
          .body__itembox--btnconteiner--left--likebtn--count
            2
        .body__itembox--btnconteiner--left--report
          .body__itembox--btnconteiner--left--report--flag
            = fa_icon"flag-o"
          .body__itembox--btnconteiner--left--report--text
            不適切な商品の報告
      .body__itembox--btnconteiner--compliance
        .body__itembox--btnconteiner--compliance--lock
          = fa_icon"lock"
        .body__itembox--btnconteiner--compliance--text
          あんしん、あんぜんへの取り組み
  .body__comment
    .body__comment--text
      相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
    .body__comment--textform
      %textarea.textarea-default{:type => "text",:name => "body"}
    .body__comment--commentbtn
      %button.body__comment--commentbtn{:type => "submit"}コメントする
  .body__prevnext
    .body__prevnext--prev
      .body__prevnext--prev--icon
        = fa_icon"chevron-left"
      .body__prevnext--prev--text
        文スト 中原中也 アクキー
    .body__prevnext--next
      .body__prevnext--next--text
        古文単語マスター333
      .body__prevnext--next--icon
        = fa_icon"chevron-right"
  .body__socialmedia
    .body__socialmedia--center
    .body__socialmedia--socialmediabox
      .body__socialmedia--socialmediabox--facebook
        .body__socialmedia--socialmediabox--facebook--facebook2
          = fa_icon"facebook-square"
      .body__socialmedia--socialmediabox--twitter
        .body__socialmedia--socialmediabox--twitter--twitter2
          = fa_icon"twitter"
      .body__socialmedia--socialmediabox--pinterest
        .body__socialmedia--socialmediabox--pinterest--pinterest2
          = fa_icon"pinterest"
  .body__itemconteiner
    .body__itemconteiner--inner
      = render partial: 'products/itemconteiner'
    .body__itemconteiner--inner2
      = render partial: 'products/itemconteiner'
-# .pankuzu
-#   .pankuzu
-#     - breadcrumb :details
-#     = breadcrumbs separator: " &rsaquo; "
.bottoms
  = render partial: 'tops/bottoms/bottom'

app/views/products/exhibit.html.haml
%body
  %div.products-information
    %header
      = render partial: 'users/us-body__header'
    = form_for @product, url: create_path, method: :post do |f|
      %main.main
        %section.center
          %div.products-box
            %h2.sell-form__header
              商品情報を入力
            .sell-form-container2
              .sell-form-container
                .sell-form-container__label
                  出品画像
                  .sell-form-container__require
                    必須
                .sell-form-container__maisuu
                  最大10枚までアップロードできます。
                = f.fields_for :images do |i|
                  %ul.preview
                    .dropzone-container
                    %div
                      %label
                        = i.file_field :url, class:"onigiri"
                        .dropzone-area
                          .input_area
                          %p
                            ドラッグアンドドロップ
                            %br
                              またはクリックしてファイルをアップロード
                    .dropzone-container2
                      %label
                        = i.file_field :url, class:"senbei"
                        .dropzone-area2
                          .input_area2
                          %p
                            ドラッグアンドドロップ
                            %br
                              またはクリックしてファイルをアップロード
            %div.products-name
              %div.products-name-box
                %label.products-name-box-head
                  商品名
                  %span.span
                    必須
                    %div.input-box
                      = f.text_field :name, {placeholder:"商品名（必須40文字まで）", class: "in" }
                      = render partial: 'devise/shared/error_messages', locals: {user: @product, column: "name"}
                  %div.products-name-box-explain
                    %label.products-name-box-explain-header
                      商品の説明
                      %span.span
                        必須
                      %div.input-box
                        = f.text_area :description, {placeholder:"商品の説明（必須1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", class: "text"}
                        = render partial: 'devise/shared/error_messages', locals: {user: @product, column: "description"}
              %div.products-to 
                %h3.products-to-details
                  商品の詳細

                %div.products-to-box
                  %div.products-to-box-form1
                    = f.label 'カテゴリー', class: 'products-to-box-form1-category'
                    %span.listing-default--require  必須 
                  
                  .selebobobo                    
                    %div.selebobo
                      = f.select :category_id, @category_parent_array, {prompt: "---"}, {class: 'selects', id: 'parent_category'}
                      %i.fa.fa-chevron-down.kitui{"aria-hidden":"ture"}
                      = render partial: 'devise/shared/error_messages', locals: {user: @product, column: "category_id"}
                    
                  %div.products-to-box-form2
                    %div.products-to-box-form2
                      = f.label '商品の状態', {class: 'products-to-box-form2-condition'}
                      %span.listing-default--require  必須

                  .selebobobobo
                    %div.selebobo
                      = f.select :state, Product.states.keys.to_a,{prompt: "---"}, {class: 'select-box'}
                      %i.fa.fa-chevron-down.kitui{"aria-hidden":"true"}
                      = render partial: 'devise/shared/error_messages', locals: {user: @product, column: "state"}

                  
              %div.products-delivery
                %h4.products-delivery-todo
                  配送について
                %a.form-question
                  ?
                %div.products-delivery-box
                  %div.products-delivery-box-form3
                    %label.products-delivery-box-form3-fee
                      配送料の負担
                      %span.listing-default--require  必須
                    .selebobobobo
                      %div.selebobo
                        = f.select :shipping_fee, Product.shipping_fees.keys.to_a,{prompt: "---"}, {class: 'select-box'}
                        %i.fa.fa-chevron-down.kitui{"aria-hidden":"true"}
                        = render partial: 'devise/shared/error_messages', locals: {user: @product, column: "shipping_fee"}

                  %div.products-delivery-box-form4
                    %label.products-delivery-box-form4-area
                      発送元の地域
                      %span.span
                        必須
                    .selobobobobo
                      %div.selebobo
                        = f.select :shipping_region, Product.shipping_regions.keys.to_a,{prompt: "---"}, {class: 'select-box'}
                        %i.fa.fa-chevron-down.kitui{"aria-hidden":"true"}
                        = render partial: 'devise/shared/error_messages', locals: {user: @product, column: "shipping_region"}

                  %div.products-delivery-box-form5
                    %label.products-delivery-box-form5-day
                      発送までの日数
                      %span.span
                        必須
                    .selobobobobo
                      %div.selebobo
                        = f.select :shipping_date, Product.shipping_dates.keys.to_a,{prompt: "---"}, {class: 'select-box'}
                        %i.fa.fa-chevron-down.kitui{"aria-hidden":"true"}
                        = render partial: 'devise/shared/error_messages', locals: {user: @product, column: "shipping_date"}

              %div.sell-price
                %h5.sell-exp
                  販売価格
                  %small
                    (300~9,999,999)
                = f.text_field :price, placeholder: "例) 300", class: "inform"
                = render partial: 'devise/shared/error_messages', locals: {user: @product, column: "price"}
                %a.form-question
                  ?
                %div.clearfix
                  %label.left
                    価格
                    %span.span
                      必須
                  %small.right  
                    ¥
                %div.hako
                %small.sale
                  販売手数料
                  %sample
                    (10%)
                  %div.rig
                    ー
                %div.hako
                %div.last
                  販売利益
                  %div.rig_2
                    = f.number_field :price, style: "display: none", id: "price"
                    ー
              %div.warning
                %p <a href="#">禁止されている出品</a>、<a href="#">行為</a>を必ずご確認ください。<br>
                %p またブランド品でシリアルナンバー等がある場合はご記載ください。
                %p <a href="#">偽ブランドの販売</a>は犯罪であ<br>り処罰される可能性があります。<br>
                %p また、出品をもちまして<a href="#">加盟店規約</a>に同意したことになります。
                = f.submit  "出品する",class: "btn-red-red",id:"peropero"
                = render partial: 'products/listingcompleted'
                =link_to "もどる" ,root_path, class: "btn-back"
    %footer.fo
      =render partial:'users/us-body__footer'
              


            

app/views/products/imgexhibit.html.haml
%li.imgexhibit__catfish
  %figure.greenday
    %img
  .imgexhibit__akumonbuttom
    %a.imgexhibit__akumonbuttom--edit
      編集
    %a.imgexhibit__akumonbuttom--delete
      削除